version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels: ["dependencies", "frontend"]
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "backend"]
    open-pull-requests-limit: 10

