name: 'Setup Environment'
description: 'Setup Java, Node.js, and other dependencies for CI/CD'
inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  setup-docker:
    description: 'Setup Docker Buildx'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Docker Buildx
      if: inputs.setup-docker == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Validate environment
      shell: bash
      run: |
        echo "Java version:"
        java -version
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        if [ "${{ inputs.setup-docker }}" == "true" ]; then
          echo "Docker version:"
          docker --version
        fi

    - name: Create build directories
      shell: bash
      run: |
        mkdir -p build/{reports,artifacts}
        echo "Build directories created"