name: 'Cache Dependencies'
description: 'Cache Gradle, npm, and other dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache npm packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          frontend/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Make Gradle wrapper executable
      shell: bash
      working-directory: ./backend
      run: chmod +x ./gradlew

    - name: Gradle dependency resolution
      shell: bash
      working-directory: ./backend
      run: ./gradlew dependencies --configuration compileClasspath > /dev/null 2>&1 || echo "Gradle dependencies resolved"

    - name: Install npm dependencies
      shell: bash
      working-directory: ./frontend
      run: |
        if [ ! -d "node_modules" ] || [ "package-lock.json" -nt "node_modules" ]; then
          npm ci --prefer-offline --no-audit --no-fund
        else
          echo "npm dependencies already cached and up to date"
        fi