global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot backend
  - job_name: 'payment-platform-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'payment-platform-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (if postgres_exporter is used)
  - job_name: 'payment-platform-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'payment-platform-redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Docker host metrics
  - job_name: 'docker-host'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s