apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-servicemonitor
  namespace: payment-platform
  labels:
    app: postgres
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
      - payment-platform
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
