import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Define the sidebar structure manually
  tutorialSidebar: [
    // Existing documentation
    'intro', // Assuming 'intro.md' is a key starting page

    // Add other top-level docs here if needed, e.g., 'another-doc'

    // Backend API Reference Category
    {
      type: 'category',
      label: 'Backend API',
      link: {
        type: 'generated-index',
        title: 'Backend API Reference',
        description: 'This section contains the auto-generated API documentation for the backend application.',
        slug: '/category/backend-api'
      },
      items: [{type: 'autogenerated', dirName: 'backend-api'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
