name: Backend CI

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew

    - name: Run Backend Tests
      run: |
        cd backend
        ./gradlew test jacocoTestReport --info

    - name: Run Spring Boot Modulith Tests
      run: |
        cd backend
        ./gradlew modulithCheck

    - name: Run Architecture Tests
      run: |
        cd backend
        ./gradlew archTest

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/build/reports/tests/

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/build/reports/jacoco/

    - name: SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd backend
        ./gradlew sonarqube \
          -Dsonar.projectKey=payment-platform_sass \
          -Dsonar.organization=payment-platform \
          -Dsonar.host.url=https://sonarcloud.io

    - name: Check Dependencies
      run: |
        cd backend
        ./gradlew dependencyCheckAnalyze