name: Documentation

on:
  push:
    paths: ['docs/**', '.github/workflows/docs.yml']
  pull_request:
    paths: ['docs/**', '.github/workflows/docs.yml']

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint markdown files
        run: npx markdownlint-cli "docs/**/*.md"

      - name: Check for broken links
        run: npx markdown-link-check docs/**/*.md --config .markdown-link-check.json

      - name: Validate documentation completeness
        run: npm run validate
        continue-on-error: true

      - name: Build documentation
        run: npm run build

      - name: Test documentation server
        run: |
          npm run serve &
          SERVER_PID=$!
          sleep 10
          curl -f http://localhost:3000 || exit 1
          kill $SERVER_PID

  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          cname: docs.platform.com