name: Frontend CI

# Test workflow trigger
on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

permissions:
  contents: read
  actions: read
  security-events: write
  pull-requests: write

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint Check
      run: |
        cd frontend
        npm run lint
        npm run prettier:check

    - name: Type Check
      run: |
        cd frontend
        npm run type-check

    - name: Run Unit Tests
      run: |
        cd frontend
        npm run test:coverage

    - name: Build Check
      run: |
        cd frontend
        npm run build

    - name: Run E2E Tests
      run: |
        cd frontend
        npm run test:e2e:ci

    - name: Upload Coverage
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage
        path: frontend/coverage/

    - name: Upload E2E Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: frontend/playwright-report/

    - name: Check for Bundle Size Changes
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "frontend/dist/**/*.{js,css,html,json}"

    - name: Run Security Audit
      run: |
        cd frontend
        npm audit